spring:
  datasource:
    url: jdbc:mysql://localhost:3306/entity_redis
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Update table configuration automatically
    show-sql: true # Display SQL statement in console
    properties:
#      javax:
#        persistence:
#          sharedCache:
#            mode: ENABLE_SELECTIVE
      hibernate:
#        format_sql: true
#        generate_statistics: true
        dialect: org.hibernate.dialect.MySQL8Dialect
      cache:
#        use_second_level_cache: true
#        use_query_cache: true
#        region:
#          factory_class: org.redisson.hibernate.RedissonRegionFactory
#        connection:
#          provider_disables_autocommit: true
        redisson-config: classpath:redisson.yaml


logging:
  level:
    root: INFO
#     org.hibernate.cache: DEBUG
